server.port: 9500
eureka.instance.hostname: eureka-server  # eureka实例的主机名
eureka.client.register-with-eureka: false #不把自己注册到eureka上
eureka.client.fetch-registry: false #不从eureka上来获取服务的注册信息
eureka.client.service-url:
eureka.client.efaultZone: http://192.168.2.209:9500/eureka/








