server:
  port: 8001

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml        # mybatis配置文件所在路径
  type-aliases-package: com.entites  						# 所有Entity别名类所在包
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml                       # mapper映射文件

spring:
   application:
    name: raigor-provider
   datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包
    url: jdbc:mysql://192.168.2.209:3306/raigor?useUnicode=true&characterEncoding=utf8&useSSL=true              # 数据库名称
    username: root
    password: 123456
    dbcp2:
      min-idle: 10                                           # 数据库连接池的最小维持连接数
      initial-size: 10                                       # 初始化连接数
      max-total: 100                                          # 最大连接数
      max-wait-millis: 200                                  # 等待连接获取的最大超时时间